name: AmazonCat
batch_size: 200

train:
  texts: train_texts.txt
  labels: train_labels.txt
  batch_size: 200
  nb_epoch: 10
  swa_warmup: 2

valid:
  size: 4000

test:
  texts: test_texts.txt
  labels: test_labels.txt

embedding:
  emb_init: emb_init.npy

label_binarizer: label_binarizer

output:
  res: results

vocab: vocab.npy

model:
  emb_size: 300
