name: EUR-Lex
batch_size: 200

train:
  texts: train_texts.txt
  labels: train_labels.txt
  batch_size: 40
  nb_epoch: 30
  swa_warmup: 10

valid:
  size: 200

test:
  texts: test_texts.txt
  labels: test_labels.txt

embedding:
  emb_init: emb_init.npy

output:
  res: EUR-Lex/results

model:
  emb_size: 300

label_binarizer: label_binarizer

vocab: vocab.npy
