name: MeSH
batch_size: 500

train:
  texts: train_texts.npy
  labels: train_labels.npy
  batch_size: 500
  nb_epoch: 33
  swa_warmup: 2

valid:
  size: 89855
  batch_size: 500

predict:
  batch_size: 200

test:
  texts: test_texts.npy

embedding:
  emb_init: MeSH/emb_init.npy

output:
  res: MeSH/results

labels_binarizer: MeSH/labels_binarizer

model:
  emb_size: 100
