name: MIMIC4
batch_size: 500

train:
  texts: train_icd10_text.txt
  labels: train_icd10_codes.txt
  nb_epoch: 33
  batch_size: 40
  swa_warmup: 2

valid:
  size: 4000

test:
  texts: test_icd10_text.txt
  labels: test_icd10_codes.txt

embedding:
  emb_init: emb_init10.npy

output:
  res: results

labels_binarizer: labels_binarizer10

model:
  emb_size: 300

vocab: vocab.npy
