name: MIMIC4Tree
foldername: MIMIC4
batch_size: 500

train:
  texts: train_icd10_text.txt
  labels: train_icd10_tree_codes.txt
  batch_size: 600
  nb_epoch: 33 # CHANGE THIS BACK
  swa_warmup: 2

valid:
  size: 4000
  batch_size: 600

predict:
  batch_size: 500

test:
  texts: test_icd10_text.txt
  labels: test_icd10_tree_codes.txt

embedding:
  emb_init: emb_init10-tree.npy

output:
  res: results10treeA

labels_binarizer: labels_binarizer10treeA

model:
  emb_size: 300

vocab: vocab.npy
