name: MIMIC2TreeA

train:
  texts: MIMIC2/train_icd10_text.npy
  labels: MIMIC2/train_icd10tree_codes.npy
  batch_size: 600
  nb_epoch: 11 # CHANGE THIS BACK
  swa_warmup: 2

valid:
  size: 4000
  batch_size: 600

predict:
  batch_size: 500

test:
  texts: MIMIC2/test_icd10_text.npy

embedding:
  emb_init: MIMIC2/emb_init10-tree.npy

output:
  res: MIMIC2/results10treeA

labels_binarizer: MIMIC2/labels_binarizer10treeA

model:
  emb_size: 300
