name: CorNetMeSHProbeNet

model:
  hidden_size: 300
  n_layers: 2
  n_probes: 5
  dropout: 0.5

train:
  batch_size: 600
  nb_epoch: 11 # CHANGE THIS BACK
  swa_warmup: 2

valid:
  batch_size: 600

predict:
  batch_size: 500

path: /localscratch/Users/gscott4/mesh2/CorNet/MIMIC2/models
